# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#Category.create({name:'Target'})
#Category.create({name:"La P'tite Chopine"})
#Category.create({name:'Design Featuring'})

#Style.create({name: 'Berliner Weiss'})
#Style.create({name: 'Belgian White'})
#Style.create({name: 'American Wheat'})
#Style.create({name: 'Weizenbier'})
#Style.create({name: 'Dunkelweizen'})
#Style.create({name: 'Lambic'})
#Style.create({name: 'Gueuze'})
#Style.create({name: 'Faro'})
#Style.create({name: 'Fruit Beer'})
#Style.create({name: 'Flanders Red'})
#Style.create({name: 'Oud Bruin'})
#Style.create({name: 'Belgian Gold'})
#Style.create({name: 'Tripel'})
#Style.create({name: 'Saison'})
#Style.create({name: 'Belgian Pale Ale'})
#Style.create({name: 'Belgian Dark Ale'})
#Style.create({name: 'Dubbel'})
#Style.create({name: 'Pale Ale'})
#Style.create({name: 'American Pale Ale'})
#Style.create({name: 'India Pale Ale'})
#Style.create({name: 'American Amber Ale'})
#Style.create({name: 'Ordinary Bitter'})
#Style.create({name: 'Special Bitter'})
#Style.create({name: 'Extra Special Bitter'})
#Style.create({name: 'Scottish light'})
#Style.create({name: 'Scottish Heavy'})
#Style.create({name: 'Scottish Export'})
#Style.create({name: 'English Mild'})
#Style.create({name: 'American Brown'})
#Style.create({name: 'English Brown'})
#Style.create({name: 'Brown Porter'})
#Style.create({name: 'Robust Porter'})
#Style.create({name: 'Dry Stout'})
#Style.create({name: 'Sweet Stout'})
#Style.create({name: 'Oatmeal Stout'})
#Style.create({name: 'Foreign Extra Stout'})
#Style.create({name: 'Imperial Stout'})
#Style.create({name: 'Russian Imperial Stout'})
#Style.create({name: 'German Pilsner'})
#Style.create({name: 'Bohemian Pilsner'})
#Style.create({name: 'American Pilsner'})
#Style.create({name: 'American light'})
#Style.create({name: 'American Standard'})
#Style.create({name: 'American Premium'})
#Style.create({name: 'American Dark'})
#Style.create({name: 'Munich Helles'})
#Style.create({name: 'Dortmunder'})
#Style.create({name: 'Munich Dunkel'})
#Style.create({name: 'Schwartzbeir'})
#Style.create({name: 'Helles Bock'})
#Style.create({name: 'Doppelbock'})
#Style.create({name: 'Traditional bock'})
#Style.create({name: 'Eisbock'})

Unit.create({name:'l'})
Unit.create({name:"cl"})
Unit.create({name:'g'})
Unit.create({name:'kg'})
